# Generated by Django 3.1 on 2021-05-18 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='省份')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='省份', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
